### ISSUE TITLE
Weird

### ISSUE THREAD

**Issue by pjebs** [rocketlaunchr/igo#3]
Having this in an igo file:

```go
func (db *DB) BeginTx(ctx context.Context, opts *stdSql.TxOptions) (*stdSql.Tx, error)
func (c *Conn) BeginTx(ctx context.Context, opts *stdSql.TxOptions) (*Tx, error)
```

generates this error during build state:

```go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x119f041]

goroutine 1 [running]:
github.com/rocketlaunchr/igo/common.RemoveComments.func1(0x12604e0, 0xc0003d2d20, 0x1260b01)
	/Users/pj/GOPATH/src/github.com/rocketlaunchr/igo/common/comments.go:36 +0x71
go/ast.inspector.Visit(0xc0002ded50, 0x12604e0, 0xc0003d2d20, 0x125f220, 0xc0002ded50)
	/usr/local/Cellar/go/1.12.6/libexec/src/go/ast/walk.go:373 +0x3a
go/ast.Walk(0x125f220, 0xc0002ded50, 0x12604e0, 0xc0003d2d20)
	/usr/local/Cellar/go/1.12.6/libexec/src/go/ast/walk.go:52 +0x66
go/ast.walkDeclList(0x125f220, 0xc0002ded50, 0xc000179e00, 0xb, 0x10)
	/usr/local/Cellar/go/1.12.6/libexec/src/go/ast/walk.go:38 +0x9e
go/ast.Walk(0x125f220, 0xc0002ded50, 0x1260460, 0xc0003caa80)
	/usr/local/Cellar/go/1.12.6/libexec/src/go/ast/walk.go:353 +0x2659
go/ast.Inspect(...)
	/usr/local/Cellar/go/1.12.6/libexec/src/go/ast/walk.go:385
github.com/rocketlaunchr/igo/common.RemoveComments(0xc000291770, 0x27, 0x13e8ea8, 0x0)
	/Users/pj/GOPATH/src/github.com/rocketlaunchr/igo/common/comments.go:33 +0x15e
github.com/rocketlaunchr/igo/cmds.processFile(0xc0003c8080, 0x9, 0x0, 0x0)
	/Users/pj/GOPATH/src/github.com/rocketlaunchr/igo/cmds/build.go:102 +0x22f
github.com/rocketlaunchr/igo/cmds.BuildCmd(0xc0000dc500, 0xc000094720, 0x1, 0x1)
	/Users/pj/GOPATH/src/github.com/rocketlaunchr/igo/cmds/build.go:40 +0x472
github.com/spf13/cobra.(*Command).execute(0xc0000dc500, 0xc0000946f0, 0x1, 0x1, 0xc0000dc500, 0xc0000946f0)
	/Users/pj/GOPATH/src/github.com/spf13/cobra/command.go:830 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000dc000, 0xc000040f78, 0x2, 0x2)
	/Users/pj/GOPATH/src/github.com/spf13/cobra/command.go:914 +0x2fc
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/pj/GOPATH/src/github.com/spf13/cobra/command.go:864
main.main()
	/Users/pj/GOPATH/src/github.com/rocketlaunchr/igo/main.go:43 +0x173

```

**Comment by pjebs** [comment]
fixed in v1.0.3
